package com.oceansoft.sndmanager.cooperate.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * XtCaseInfo generated by MyEclipse Persistence Tools
 */

public class XtCaseInfo implements java.io.Serializable {

	/**
	 * 
	 */											  				

	/**
	 * 
	 */
	private static final long serialVersionUID = 3624782867980459932L;

	/**
	 * 
	 */
	/**
	 * 
	 */

	/**
	 * 案件编号
	 */
	private String caseId;
	/**
	 * 案卷编号
	 */

	private String caseCode;
	/**
	 * 问题来源
	 */
	private String quesResource;
	/**
	 * 来源渠道
	 */

	private String quesChannel;
	/**
	 * 案件类型
	 */

	private String caseType;
	/**
	 * 案件名称
	 */

	private String caseName;
	/**
	 * 举报人
	 */

	private String reporter;
	/**
	 * 上报时间
	 */

	private Date reportTime;
	/**
	 * 举报人联系方式
	 */

	private String reporterInfo;
	/**
	 * 案件描述
	 */

	private String questionDesc;
	/**
	 * 发生时间
	 */

	private Date occurTime;
	/**
	 * 立案时间
	 */

	private Date registerTime;
	/**
	 * 结案时间
	 */

	private Date closeTime;
	/**
	 * 案件状态
	 */

	private String caseStatus;
	/**
	 * 影响范围描述
	 */

	private String effRangeDesc;
	/**
	 * 影响范围量级
	 */

	private String effRangeLevel;
	/**
	 * 量级单位
	 */

	private String levelUnit;
	/**
	 * 损坏程度
	 */

	private String demageLevel;
	/**
	 * 部件信息
	 */

	private String compNo;
	/**
	 * 位置描述
	 */

	private String positionDesc;
	/**
	 * 坐标X
	 */

	private Double posX;
	/**
	 * 坐标Y
	 */

	private Double posY;
	/**
	 * 所属网格
	 */

	private String bgcode;
	/**
	 * 所属区域
	 */

	private String regionId;
	/**
	 * 
	 */

	private String regionName;
	/**
	 * 附件列表
	 */

	private String attachList;
	/**
	 * 工作流编号
	 */

	private String workflowId;
	/**
	 * 当前处置部门
	 */
	
	private String currOrg;
	/**
	 * 备注
	 */

	private String note;
	/**
	 * 
	 */

	private String caseLevel;
	/**
	 * 
	 */

	private Set<XtCaseDetail> xtCaseDetails = new HashSet<XtCaseDetail>(0);
	/**
	 * 
	 */

	private String caseLevelName;
	/**
	 * 
	 */

	private String caseStatusName;
	/**
	 * 
	 */

	private String caseTypeName;
	/**
	 * 
	 */

	private String caseBigTypeName;
	/**
	 * 
	 */

	private String caseSmallTypeName;
	/**
	 * 
	 */

	private String street;
	/**
	 *  问题来源名称
	 */

	private String questionResourceName; 
	/**
	 * 问题来源渠道名称
	 */

	private String questionChannelName; 
	/**
	 * 破坏级别名称
	 */

	private String demageLevelName; 
	/**
	 * 
	 */

	private String community;
	/**
	 *  green: 绿灯（表示案件正常）
	 red：红灯（表示案件超时）
	 yellow：黄灯（表示案件接近超时）
	 */
	private String lampColor;
	/**
	 *判断案件是否已经督办 
	 */

	private String isSupervised; 
	/**
	 * 是否派遣到业务系统
	 */
	private String isDispatch; 
	/**
	 * 
	 */
	private String grid;
	/**
	 * 
	 */

	private String demageName;
	/**
	 * 
	 */
	private String withdrawTrace;
	/**
	 * 
	 */
	private String levelUnitName;
	/**
	 * 
	 */
	private String extChar;
	/**
	 * 
	 */
	private Double extNumber;
	/**
	 *处置时限
	 */
	private Date extDate;
	/**
	 * 拒绝时限 hfq 091111
	 */
	private Date refuseOTime; 
	/**
	 * 满意度
	 */
	private String satisfyDegree;
	/**
	 * 
	 */
	private String satisfy;
	/**
	 * 
	 */
	private String reportDesc;
	/**
	 *延时跟踪 
	 */
	private String ys;
	/**
	 * 延时跟踪
	 */
	private String gz;
	/**
	 * wsm to add at 20091027
	 */
	private String isCuiban;
	

	// 以下6个变量用于案件列表页面右侧现实
	/**
	 *   受理时间
	 */
	private Date acceptDate;
	/**
	 * 办理时间
	 */
	private Date disposeDate;
	/**
	 *  签收时间
	 */
	private Date signInDate;

	private int cuibancount;

	private int dubancount;

	private Double timeout;

	private String orgList;
	
	
	private int traceCount;
	/**
	 * 新添字段存 市城管工单是否返回给新系统 v2标示
	 */
	private String scgjType;
	private String reply2h;
	private String   returnVisitFlag;//回访标示，0 不需要，1需要
	
	/**便民再交办/转交办意见**/
	private String acceptopinion;
	/**回访意见**/
	private String returnvisitopinion;
	/**满意度**/
	private String satisfactionlevel;



	public String getCurrOrg() {
		return currOrg;
	}

	public void setCurrOrg(String currOrg) {
		this.currOrg = currOrg;
	}

	public int getTraceCount() {
		return traceCount;
	}

	public void setTraceCount(int traceCount) {
		this.traceCount = traceCount;
	}

	public String getOrgList() {
		return orgList;
	}

	public void setOrgList(String orgList) {
		this.orgList = orgList;
	}

	public Date getAcceptDate() {
		return acceptDate;
	}

	public void setAcceptDate(Date acceptDate) {
		this.acceptDate = acceptDate;
	}

	public Date getDisposeDate() {
		return disposeDate;
	}

	public void setDisposeDate(Date disposeDate) {
		this.disposeDate = disposeDate;
	}

	public Date getSignInDate() {
		return signInDate;
	}

	public void setSignInDate(Date signInDate) {
		this.signInDate = signInDate;
	}

	public String getGrid() {
		// grid=new StringBuilder(this.getStreet()).append("
		// ").append(this.getCommunity()).append("
		// ").append(this.getBgcode()).toString();
		// grid=(null==getStreet()?"":getStreet())+"
		// "+(null==getCommunity()?"":getCommunity())+"
		// "+(null==getBgcode()?"":getBgcode());
		return grid;
	}

	public void setGrid(String grid) {
		this.grid = grid;
	}

	// Constructors

	/** default constructor */
	public XtCaseInfo() {
	}

	/** minimal constructor */
	public XtCaseInfo(String caseId, String caseType, String questionDesc, Date occurTime, String caseStatus,
			String positionDesc, Double posX, Double posY, String bgcode, String regionId) {
		this.caseId = caseId;
		this.caseType = caseType;
		this.questionDesc = questionDesc;
		this.occurTime = occurTime;
		this.caseStatus = caseStatus;
		this.positionDesc = positionDesc;
		this.posX = posX;
		this.posY = posY;
		this.bgcode = bgcode;
		this.regionId = regionId;
	}

	public XtCaseInfo(String caseId, String caseStatusName, String caseTypeName, int cuibancount, Date occurTime,
			String street, String community, Double timeout, Date reportTime, String orgList, String satisfy,
			String caseName, String isDispatch) {
		this.caseId = caseId;
		this.caseStatusName = caseStatusName;
		this.caseTypeName = caseTypeName;
		this.cuibancount = cuibancount;
		this.occurTime = occurTime;
		this.street = street;
		this.community = community;
		this.timeout = timeout;
		this.reportTime = reportTime;
		this.orgList = orgList;
		this.satisfy = satisfy;
		this.caseName = caseName;
		this.isDispatch = isDispatch;

	}

	public XtCaseInfo(String caseId, String caseStatus, String caseStatusName, String quesResource,
			String caseTypeName, String caseBigTypeName, String caseSmallTypeName, Date reportTime, String orgList,
			String satisfy) {
		this.caseId = caseId;
		this.caseStatus = caseStatus;
		this.caseStatusName = caseStatusName;
		this.quesResource = quesResource;
		this.caseTypeName = caseTypeName;
		this.caseBigTypeName = caseBigTypeName;
		this.caseSmallTypeName = caseSmallTypeName;
		this.reportTime = reportTime;
		this.orgList = orgList;
		this.satisfy = satisfy;
	}

	public XtCaseInfo(String caseId, String caseStatusName, String caseTypeName, String caseBigTypeName,
			String caseSmallTypeName, Date reportTime, String orgList, String satisfy) {
		this.caseId = caseId;
		this.caseStatusName = caseStatusName;
		this.caseTypeName = caseTypeName;
		this.caseBigTypeName = caseBigTypeName;
		this.caseSmallTypeName = caseSmallTypeName;
		this.reportTime = reportTime;
		this.orgList = orgList;
		this.satisfy = satisfy;

	}

	/** full constructor */
	public XtCaseInfo(String caseId, String caseCode, String quesResource, String quesChannel, String caseType,
			String caseName, String reporter, Date reportTime, String reporterInfo, String questionDesc,
			Date occurTime, Date registerTime, Date closeTime, String caseStatus, String effRangeDesc,
			String effRangeLevel, String levelUnit, String demageLevel, String compNo, String positionDesc,
			Double posX, Double posY, String bgcode, String regionId, String attachList, String workflowId,
			String note, Set<XtCaseDetail> xtCaseDetails,String returnVisitFlag) {
		this.caseId = caseId;
		this.caseCode = caseCode;
		this.quesResource = quesResource;
		this.quesChannel = quesChannel;
		this.caseType = caseType;
		this.caseName = caseName;
		this.reporter = reporter;
		this.reportTime = reportTime;
		this.reporterInfo = reporterInfo;
		this.questionDesc = questionDesc;
		this.occurTime = occurTime;
		this.registerTime = registerTime;
		this.closeTime = closeTime;
		this.caseStatus = caseStatus;
		this.effRangeDesc = effRangeDesc;
		this.effRangeLevel = effRangeLevel;
		this.levelUnit = levelUnit;
		this.demageLevel = demageLevel;
		this.compNo = compNo;
		this.positionDesc = positionDesc;
		this.posX = posX;
		this.posY = posY;
		this.bgcode = bgcode;
		this.regionId = regionId;
		this.attachList = attachList;
		this.workflowId = workflowId;
		this.note = note;
		this.xtCaseDetails = xtCaseDetails;
		this.returnVisitFlag=returnVisitFlag;
	}
	
	
	
	
	
	/**
	 * add by qiur  
	 * 用于代进驻单位处置的查询
	 * @param caseId
	 * @param workflowId
	 * @param caseStatusName
	 * @param extChar
	 * @param extDate
	 */
	public XtCaseInfo(String caseId, String extChar, String workflowId, String caseStatusName, Date extDate) {
		super();
		this.caseId = caseId;
		this.workflowId = workflowId;
		this.caseStatusName = caseStatusName;
		this.extChar = extChar;
		this.extDate = extDate;
	}

	// Property accessors

	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getCaseCode() {
		return this.caseCode;
	}

	public void setCaseCode(String caseCode) {
		this.caseCode = caseCode;
	}

	public String getQuesResource() {
		return this.quesResource;
	}

	public void setQuesResource(String quesResource) {
		this.quesResource = quesResource;
	}

	public String getQuesChannel() {
		return this.quesChannel;
	}

	public void setQuesChannel(String quesChannel) {
		this.quesChannel = quesChannel;
	}

	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	public String getCaseName() {
		return this.caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	public String getReporter() {
		return this.reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}

	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public String getReporterInfo() {
		return this.reporterInfo;
	}

	public void setReporterInfo(String reporterInfo) {
		this.reporterInfo = reporterInfo;
	}

	public String getQuestionDesc() {
		return this.questionDesc;
	}

	public void setQuestionDesc(String questionDesc) {
		this.questionDesc = questionDesc;
	}

	public Date getOccurTime() {
		return this.occurTime;
	}

	public void setOccurTime(Date occurTime) {
		this.occurTime = occurTime;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public String getEffRangeDesc() {
		return this.effRangeDesc;
	}

	public void setEffRangeDesc(String effRangeDesc) {
		this.effRangeDesc = effRangeDesc;
	}

	public String getEffRangeLevel() {
		return this.effRangeLevel;
	}

	public void setEffRangeLevel(String effRangeLevel) {
		this.effRangeLevel = effRangeLevel;
	}

	public String getLevelUnit() {
		return this.levelUnit;
	}

	public void setLevelUnit(String levelUnit) {
		this.levelUnit = levelUnit;
	}

	public String getDemageLevel() {
		return this.demageLevel;
	}

	public void setDemageLevel(String demageLevel) {
		this.demageLevel = demageLevel;
	}

	public String getCompNo() {
		return this.compNo;
	}

	public void setCompNo(String compNo) {
		this.compNo = compNo;
	}

	public String getPositionDesc() {
		return this.positionDesc;
	}

	public void setPositionDesc(String positionDesc) {
		this.positionDesc = positionDesc;
	}

	public Double getPosX() {
		return this.posX;
	}

	public void setPosX(Double posX) {
		this.posX = posX;
	}

	public Double getPosY() {
		return this.posY;
	}

	public void setPosY(Double posY) {
		this.posY = posY;
	}

	public String getBgcode() {
		return this.bgcode;
	}

	public void setBgcode(String bgcode) {
		this.bgcode = bgcode;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getAttachList() {
		return this.attachList;
	}

	public void setAttachList(String attachList) {
		this.attachList = attachList;
	}

	public String getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(String workflowId) {
		this.workflowId = workflowId;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getCaseLevel() {
		return caseLevel;
	}

	public void setCaseLevel(String caseLevel) {
		this.caseLevel = caseLevel;
	}

	public Set<XtCaseDetail> getXtCaseDetails() {
		return this.xtCaseDetails;
	}

	public void setXtCaseDetails(Set<XtCaseDetail> xtCaseDetails) {
		this.xtCaseDetails = xtCaseDetails;
	}

	public void setCaseTypeName(String caseTypeName) {
		this.caseTypeName = caseTypeName;
	}

	public void setCaseBigTypeName(String caseBigTypeName) {
		this.caseBigTypeName = caseBigTypeName;
	}

	public String getCaseTypeInfo() {
		String caseTypeInfo = (null == caseTypeName ? "" : caseTypeName) + " "
				+ (null == caseBigTypeName ? "" : caseBigTypeName) + " "
				+ (null == caseSmallTypeName ? "" : caseSmallTypeName);
		return caseTypeInfo;
	}

	public void setCaseTypeInfo(String str) {
	}

	public String getCaseTypeName() {
		return this.caseTypeName;
	}

	public String getCaseBigTypeName() {
		return this.caseBigTypeName;
	}

	public String getCaseStatusName() {
		return caseStatusName;
	}

	public void setCaseStatusName(String caseStatusName) {
		this.caseStatusName = caseStatusName;
	}

	public void setCommunity(String community) {
		this.community = community;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCommunity() {
		return this.community;
	}

	public String getCaseSmallTypeName() {
		return caseSmallTypeName;
	}

	public void setCaseSmallTypeName(String caseSmallTypeName) {
		this.caseSmallTypeName = caseSmallTypeName;
	}

	public String getCaseLevelName() {
		return caseLevelName;
	}

	public void setCaseLevelName(String caseLevelName) {
		this.caseLevelName = caseLevelName;
	}

	public String getQuestionResourceName() {
		return questionResourceName;
	}

	public void setQuestionResourceName(String questionResourceName) {
		this.questionResourceName = questionResourceName;
	}

	public String getQuestionChannelName() {
		return questionChannelName;
	}

	public void setQuestionChannelName(String questionChannelName) {
		this.questionChannelName = questionChannelName;
	}

	public String getDemageLevelName() {
		return demageLevelName;
	}

	public void setDemageLevelName(String demageLevelName) {
		this.demageLevelName = demageLevelName;
	}

	public String getDemageName() {
		return demageName;
	}

	public void setDemageName(String demageName) {
		this.demageName = demageName;
	}

	public String getLampColor() {
		return lampColor;
	}

	public void setLampColor(String lampColor) {
		this.lampColor = lampColor;
	}

	public String getIsSupervised() {
		return isSupervised;
	}

	public void setIsSupervised(String isSupervised) {
		this.isSupervised = isSupervised;
	}

	public String getLevelUnitName() {
		return levelUnitName;
	}

	public void setLevelUnitName(String levelUnitName) {
		this.levelUnitName = levelUnitName;
	}

	public String getExtChar() {
		return extChar;
	}

	public void setExtChar(String extChar) {
		this.extChar = extChar;
	}

	public Double getExtNumber() {
		return extNumber;
	}

	public void setExtNumber(Double extNumber) {
		this.extNumber = extNumber;
	}

	public Date getExtDate() {
		return extDate;
	}

	public void setExtDate(Date extDate) {
		this.extDate = extDate;
	}

	public String getRegionName() {
		return regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public String getIsCuiban() {
		return isCuiban;
	}

	public void setIsCuiban(String isCuiban) {
		this.isCuiban = isCuiban;
	}

	public int getCuibancount() {
		return cuibancount;
	}

	public void setCuibancount(int cuibancount) {
		this.cuibancount = cuibancount;
	}

	public int getDubancount() {
		return dubancount;
	}

	public void setDubancount(int dubancount) {
		this.dubancount = dubancount;
	}

	public Double getTimeout() {
		return timeout;
	}

	public void setTimeout(Double timeout) {
		this.timeout = timeout;
	}

	public String getSatisfyDegree(String string) {
		return satisfyDegree;
	}

	public void setSatisfyDegree(String satisfyDegree) {
		this.satisfyDegree = satisfyDegree;
	}

	public String getSatisfy() {
		return satisfy;
	}

	public void setSatisfy(String satisfy) {
		this.satisfy = satisfy;
	}

	public String getReportDesc() {
		return reportDesc;
	}

	public void setReportDesc(String reportDesc) {
		this.reportDesc = reportDesc;
	}

	public Date getRefuseOTime() {
		return this.refuseOTime;
	}

	public void setRefuseOTime(Date refuseOTime) {
		this.refuseOTime = refuseOTime;
	}

	public String getWithdrawTrace() {
		return withdrawTrace;
	}

	public void setWithdrawTrace(String withdrawTrace) {
		this.withdrawTrace = withdrawTrace;
	}

	public String getYs() {
		return ys;
	}

	public void setYs(String ys) {
		this.ys = ys;
	}

	public String getGz() {
		return gz;
	}

	public void setGz(String gz) {
		this.gz = gz;
	}

	public String getIsDispatch() {
		return isDispatch;
	}

	public void setIsDispatch(String isDispatch) {
		this.isDispatch = isDispatch;
	}

	// 申请跟踪或延时次数
	private int applyCount;

	public int getApplyCount() {
		return applyCount;
	}

	public void setApplyCount(int applyCount) {
		this.applyCount = applyCount;
	}

	public String getScgjType() {
		return scgjType;
	}

	public void setScgjType(String scgjType) {
		this.scgjType = scgjType;
	}

	public String getReply2h() {
		return reply2h;
	}

	public void setReply2h(String reply2h) {
		this.reply2h = reply2h;
	}

	public String getReturnVisitFlag() {
		return returnVisitFlag;
	}

	public void setReturnVisitFlag(String returnVisitFlag) {
		this.returnVisitFlag = returnVisitFlag;
	}

	public String getReturnvisitopinion() {
		return returnvisitopinion;
	}

	public void setReturnvisitopinion(String returnvisitopinion) {
		this.returnvisitopinion = returnvisitopinion;
	}

	
	public String getSatisfactionlevel() {
		return satisfactionlevel;
	}

	public void setSatisfactionlevel(String satisfactionlevel) {
		this.satisfactionlevel = satisfactionlevel;
	}

	public String getSatisfyDegree() {
		return satisfyDegree;
	}

	public String getAcceptopinion() {
		return acceptopinion;
	}

	public void setAcceptopinion(String acceptopinion) {
		this.acceptopinion = acceptopinion;
	}
	
	
	
	
}